/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iPersonSol from "./IPerson.sol";
export { Person__factory } from "./Person__factory";
export { Persons__factory } from "./Persons__factory";
