/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IPerson, IPersonInterface } from "../IPerson";

const _abi = [
  {
    inputs: [],
    name: "getPerson",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "age",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPerson__factory {
  static readonly abi = _abi;
  static createInterface(): IPersonInterface {
    return new Interface(_abi) as IPersonInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPerson {
    return new Contract(address, _abi, runner) as unknown as IPerson;
  }
}
