/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPersonSol from "./IPerson.sol";
export type { iPersonSol };
export type { Person } from "./Person";
export type { Persons } from "./Persons";
export * as factories from "./factories";
export type { IPersons } from "./IPerson.sol/IPersons";
export { IPersons__factory } from "./factories/IPerson.sol/IPersons__factory";
export { Person__factory } from "./factories/Person__factory";
export { Persons__factory } from "./factories/Persons__factory";
